name: todo_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.0.8
  flutter_neumorphic: 3.2.0
  intl: 0.17.0

  injectable: 2.1.1
  get_it: 7.2.0
  provider: 6.0.5
  firebase_messaging: 14.3.0
  firebase_auth: 4.2.3
  firebase_core: 2.8.0
  cloud_firestore: 4.4.5
  desktop_webview_auth: 0.0.11
  cupertino_icons: 1.0.2
  rxdart: 0.27.7
  flutter_local_notifications: 13.0.0
  vibration: 1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  static_analyze_av: ^0.2.3
  flutter_native_timezone: 2.0.0

  injectable_generator: 2.1.5
  build_runner: 2.3.3

  flutter_lints: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Rubik-Regular
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
